In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
##Importanto o dataset

In [29]:
df = pd.read_csv('Churn_Modelling.csv')

## PRÉ-PROCESSAMENTO DE DADOS

In [30]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [31]:
df = df.drop(['RowNumber', 'CustomerId'], axis=1)

In [32]:
df.head()

Surname  CreditScore Geography  Gender  Age  Tenure    Balance  \
0  Hargrave          619    France  Female   42       2       0.00   
1      Hill          608     Spain  Female   41       1   83807.86   
2      Onio          502    France  Female   42       8  159660.80   
3      Boni          699    France  Female   39       1       0.00   
4  Mitchell          850     Spain  Female   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0              1          1               1        101348.88       1  
1              1          0               1        112542.58       0  
2              3          1               0        113931.57       1  
3              2          0               0         93826.63       0  
4              1          1               1         79084.10       0

In [33]:
df.Surname.value_counts()

Smith         32
Scott         29
Martin        29
Walker        28
Brown         26
Shih          25
Yeh           25
Genovese      25
Wright        24
Maclean       24
Fanucci       23
Wilson        23
Ma            23
White         23
Johnson       22
Moore         22
Chu           22
Lu            22
Wang          22
Mai           21
McGregor      21
Thompson      21
Sun           21
Kerr          20
Fang          20
Graham        20
Trevisani     20
Kao           20
Miller        20
Mitchell      20
              ..
Gleeson        1
Ndubuisi       1
Loane          1
Hammer         1
Metcalf        1
Nyhan          1
Kentish        1
Kinlaw         1
Ochoa          1
Dann           1
Glauert        1
D'Albertis     1
McGuirk        1
Nina           1
Uren           1
Denman         1
O'Toole        1
Kendall        1
Steiner        1
Barnhill       1
Sauve          1
Hallahan       1
Rishel         1
Innes          1
Ewen           1
Ruse           1
Griffen        1
Coburn        

In [34]:
df.drop('Surname', axis=1, inplace=True)

In [35]:
df.tail()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0

In [36]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [41]:
df.loc[df.Geography=='France','cod_Geography'] = 1
df.loc[df.Geography=='Spain','cod_Geography']  = 2
df.loc[df.Geography=='Germany','cod_Geography'] = 3

In [42]:
df[['cod_Geography','Geography']]

cod_Geography Geography
0               1.0    France
1               2.0     Spain
2               1.0    France
3               1.0    France
4               2.0     Spain
5               2.0     Spain
6               1.0    France
7               3.0   Germany
8               1.0    France
9               1.0    France
10              1.0    France
11              2.0     Spain
12              1.0    France
13              1.0    France
14              2.0     Spain
15              3.0   Germany
16              3.0   Germany
17              2.0     Spain
18              2.0     Spain
19              1.0    France
20              1.0    France
21              2.0     Spain
22              2.0     Spain
23              1.0    France
24              1.0    France
25              1.0    France
26              3.0   Germany
27              1.0    France
28              3.0   Germany
29              1.0    France
...             ...       ...
9970            1.0    France
9971            1.0    France
9972            1.0    France
9973            1.0    France
9974            1.0    France
9975            3.0   Germany
9976            1.0    France
9977            1.0    France
9978            1.0    France
9979            1.0    France
9980            2.0     Spain
9981            3.0   Germany
9982            3.0   Germany
9983            1.0    France
9984            3.0   Germany
9985            1.0    France
9986            3.0   Germany
9987            2.0     Spain
9988            1.0    France
9989            2.0     Spain
9990            3.0   Germany
9991            1.0    France
9992            2.0     Spain
9993            1.0    France
9994            1.0    France
9995            1.0    France
9996            1.0    France
9997            1.0    France
9998            3.0   Germany
9999            1.0    France

[10000 rows x 2 columns]

In [48]:
df.drop('Geography', axis=1, inplace=True)

In [49]:
df.Gender.unique()

array([1, 2])

In [50]:
df.loc[df.Gender=='Female','Gender'] = 1
df.loc[df.Gender=='Male','Gender'] = 2
df.head(6)

/home/sandeco/.local/lib/python3.6/site-packages/pandas/core/ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       1   42       2       0.00              1          1   
1          608       1   41       1   83807.86              1          0   
2          502       1   42       8  159660.80              3          1   
3          699       1   39       1       0.00              2          0   
4          850       1   43       2  125510.82              1          1   
5          645       2   44       8  113755.78              2          1   

   IsActiveMember  EstimatedSalary  Exited  cod_Geography  
0               1        101348.88       1            1.0  
1               1        112542.58       0            2.0  
2               0        113931.57       1            1.0  
3               0         93826.63       0            1.0  
4               1         79084.10       0            2.0  
5               0        149756.71       1            2.0

In [51]:
X = np.array(df.drop("Exited", axis=1))

In [52]:
X

array([[6.1900000e+02, 1.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        1.0134888e+05, 1.0000000e+00],
       [6.0800000e+02, 1.0000000e+00, 4.1000000e+01, ..., 1.0000000e+00,
        1.1254258e+05, 2.0000000e+00],
       [5.0200000e+02, 1.0000000e+00, 4.2000000e+01, ..., 0.0000000e+00,
        1.1393157e+05, 1.0000000e+00],
       ...,
       [7.0900000e+02, 1.0000000e+00, 3.6000000e+01, ..., 1.0000000e+00,
        4.2085580e+04, 1.0000000e+00],
       [7.7200000e+02, 2.0000000e+00, 4.2000000e+01, ..., 0.0000000e+00,
        9.2888520e+04, 3.0000000e+00],
       [7.9200000e+02, 1.0000000e+00, 2.8000000e+01, ..., 0.0000000e+00,
        3.8190780e+04, 1.0000000e+00]])

In [53]:
y = np.array(df.Exited)

In [54]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [56]:
from sklearn.neighbors import KNeighborsClassifier

In [57]:
knn = KNeighborsClassifier(n_neighbors=3)

In [58]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [59]:
knn.score(X_test, y_test)

0.739